version: '3'

services:

  phpfpm_bestit:
    build: ./php8/
    restart: always
    volumes:
      - ./bestit:/var/www/html
    depends_on:
      - mariadb
    container_name: phpfpm_bestit
    networks:
      - backend

  apache_bestit:
    build: ./apache_bestit/
    restart: always
    ports:
      - 8085:80
    volumes:
      - ./bestit:/var/www/html
    container_name: apache_bestit
    depends_on:
      - phpfpm_bestit
      - mariadb
    networks:
      - backend
      - frontend

  mariadb:
    image: mariadb:10.3
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/mariadb-data:/var/lib/mysql
      - ./mariadb/mariadb-data/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=5000M
      - MEMORY_LIMIT=5012M
      - MAX_EXECUTION_TIME=6000
      - MYSQL_DATABASE="${DB_NAME}"
      - MYSQL_USER="${DB_USERNAME}"
      - MYSQL_PASSWORD="${DB_PASSWORD}"
    depends_on:
      - mariadb
    networks:
      - backend

volumes:
  mariadb-data:
  
networks:
  frontend:
  backend: